version: "3.8"

services:
  mongo-database:
    container_name: mongo-database
    image: mongo:6.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-data:/data/db
    networks:
      - app

  mysql-database:
    container_name: mysql-database
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    networks:
      - app

networks:
  app:
    driver: bridge
