version: "3.8"

services:
  mysql:
      container_name: mysql
      image: mysql:8.0
      environment:
        - MYSQL_DATABASE=orderdb
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - "3306:3306"
      volumes:
        - db:/var/lib/mysql
      networks:
        - order-service

volumes:
  db:

networks:
  order-service:
    driver: bridge