server:
    port: 8082

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/orderdb
        username: root
        password: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        # properties:
        #     hibernate:
        #         dialect: org.hibernate.dialect.MySQL5Dialect