server:
  port: 8081

spring:
  application:
    name: product-service
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: product
      port: 27017
      host: localhost
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
