server:
  port: 8081

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: productdb
      port: 27017
      host: localhost
      auto-index-creation: true
