version: "3.8"

services:
  mysql-inventory-service:
    container_name: mysql-inventory-service
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=inventorydb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - inventory-service

volumes:
  db:

networks:
  inventory-service:
    driver: bridge
